title: Shehbaz Malik - Full-Stack Developer
description: Portfolio of Shehbaz Malik, a Full-Stack Developer specializing in PHP, Laravel, React.js, NodeJS, and AI integrations.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
resume_link: https://drive.google.com/drive/folders/1Y2sesM0rnAVnB4pXGEh53Dg8yCamx9oz?usp=sharing
linkedin_link: https://www.linkedin.com/in/shehbaz--malik
github_link: https://github.com/shehbaz-malik
google_analytics: G-24L1K58KVD
google_analytics_script: https://www.googletagmanager.com/gtag/js?id=G-24L1K58KVD
htmlproofer:
  check_external_hash: false