title: Shehbaz Malik - Full-Stack Developer
description: Portfolio of Shehbaz Malik
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
resume_link: https://drive.google.com/drive/folders/1Y2sesM0rnAVnB4pXGEh53Dg8yCamx9oz?usp=sharing
linkedin_link: https://www.linkedin.com/in/pro-remote-web-developer
github_link: https://github.com/cykadev